### ISSUE TITLE
Error when trying to setup the wrapper : TypeError: api.account is not a function

### ISSUE THREAD

**Issue by obrassard** [matt-major/do-wrapper#38]
Hello ! I am trying your DigitalOcean API wrapper, however I am not able to make it work even if I follow the instructions provided in the Readme file. Indeed, I get an error when I am trying to use api functions such as `account` : `TypeError: api.account is not a function`

Here's my code :
```js
var DigitalOcean = require('do-wrapper').default;
var api = new DigitalOcean('my-api-token', 5);
api.account().then((data) => {
    console.log(data.body);
});
```

Output : 
```
api.account().then((data) => {
    ^

TypeError: api.account is not a function
    at Object.<anonymous> (/Users/obrassard/Desktop/test.js:4:5)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by obrassard** [comment]
I just noticed that this issue concern the version 4.0.0 only, indeed this code works on version ^3.25.4. So it might just be a documentation issue
